spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      max-poll-records: 100
    listener:
      poll-timeout: 3000
      missing-topics-fatal: false

data-process:
  bootstrap-servers: "172.17.1.31:30892"
  kafka-source-topic: "connect_source_test"
  default-kafka-target-topic: "connect_sink_test_todb"
  consumer-group-id: "connect-transform:test_todb"
  #对应kafka-connect任务的名称
  task-name: "mysql_test_tokafka"
  schema-class:  com.demo.kafka.User
