https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 40018

spring:
  profiles:
    active: dev
wu:
  database:
    mapper:
      scan-xml-path: classpath*:wu-mapper/*Dao.xml

#debug: true



