https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 2018

spring:
  profiles:
    active: wjw
  wu:
    shiro:
      verification: session
wu:
  database:
    mapper:
      scan-xml-path: classpath*:wu-mapper/*Dao.xml

#debug: true
mybatis:
  mapperLocations: classpath:mapper/**/*.xml


#hbase配置，端口默认2181，
hbase:
  conf:
    confMaps:
      'hbase.zookeeper.quorum': 'k8s.wu2020.top:2181'



