spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: supconit
          url: jdbc:mysql://172.17.1.58:30806/upms_itt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver