https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 2018

spring:
  profiles:
    active: zz
  wu:
    shiro:
      verification: session
wu:
  database:
    mapper:
      scan-xml-path: classpath*:wu-mapper/*Dao.xml

#debug: true
mybatis:
  mapperLocations: classpath:mapper/**/*.xml



