server:
  port: 1180

spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: wujiawei
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver

  wu:
    database:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: wujiawei
    dynamic:
      database:
        enable: false
        database-config-map:
          master:
            driver: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/test
            username: root
            password: wujiawei
#          localhost:
#            driver: com.mysql.jdbc.Driver
#            url: jdbc:mysql://127.0.0.1:3306/test
#            username: root
#            password: wujiawei
wu:
  database:
    mapper:
      scan-xml-path: classpath*:wu-mapper/*Dao.xml

debug: false
easy:
  upsert:
    config:
      print-sql: false
      batch-limit: 10000

