server:
  port: 1180

spring:
  profiles:
    active: mb-dy

  elasticsearch:
    rest:
      uris: "http://k8s.wu2020.top:9200"
  jpa:
    show-sql: true
  activemq:
    broker-url: 127.0.0.1:6631
  redis:
    host: www.wu2020.top
    password: 123456
  rsocket:
    server:
      address: 127.0.0.1
  application:
    name: temple



debug: false
easy:
  upsert:
    config:
      print-sql: false
      batch-limit: 10000
      record-log: true
nacos:
  config:
    server-addr: www.wu2020.top:8848
    namespace: public

