server:
  port: 1180

spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: wujiawei
          url: jdbc:mysql://www.wu2020.top:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver

#  wu:
#    database:
#      driver: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/test
#      username: root
#      password: wujiawei
#    dynamic:
#      database:
#        enable: false
#        database-config-map:
#          master:
#            driver: com.mysql.jdbc.Driver
#            url: jdbc:mysql://127.0.0.1:3306/test
#            username: root
#            password: wujiawei
  elasticsearch:
    rest:
      uris: "http://k8s.wu2020.top:9200"
  jpa:
    show-sql: true
  activemq:
    broker-url: 127.0.0.1:6631
  redis:
    host: www.wu2020.top
    password: 123456
  rsocket:
    server:
      address: 127.0.0.1
  application:
    name: temple
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          socket-timeout: 1800
#          localhost:
#            driver: com.mysql.jdbc.Driver
#            url: jdbc:mysql://127.0.0.1:3306/test
#            username: root
#            password: wujiawei

debug: false
easy:
  upsert:
    config:
      print-sql: false
      batch-limit: 10000
      record-log: true
nacos:
  config:
    server-addr: www.wu2020.top:8848
    namespace: public

